### ISSUE TITLE
Add $absolute flag to UniformResourceLocator::getPaths

### ISSUE THREAD

**Issue by alexweissman** [rockettheme/toolbox#12]
It would be useful to have an $absolute flag for `getPaths`.  Otherwise, I have to call `getBase`, and then loop through `getPaths` to manually prepend the base.  I could do a PR for this, if anyone is interested.

**Comment by mahagr** [comment]
Go ahead and do it. Where you would use this?

**Comment by alexweissman** [comment]
I've been using a `locator` object as a sort of repository for search paths.  The problem is that when I want to initialize the search paths for Twig, I need some way to get them out of my `locator` - `getPaths` only returns relative paths and Twig requires absolute paths.

It does seem that `findResources('templates://', true, true);` will work to give me the absolute paths.  So perhaps, the flag in `getPaths` is not necessary after al.

**Comment by mahagr** [comment]
Yes, `findresources()` can give you all the paths. Thats how we feed twig.

**Comment by alexweissman** [comment]
Could you link me to that code, actually?

**Comment by mahagr** [comment]
Twig code? Yeah:

https://github.com/gantry/gantry5/blob/develop/src/classes/Gantry/Admin/Theme.php#L113-L126

That's probably the simplest example I have.
