### ISSUE TITLE
Particles are going overlapped when going to 'responsive'

### ISSUE THREAD

**Issue by dimidino** [rockettheme/toolbox#15]
Hello!

(I'm not sure if this is the right forum, please if it is not - tell me the right one and you do not hate me! ;) )

In general, the site is not very good and mobile friendly and should be worked on, but for now I would be happy if someone help me with the solution of this problem here (see the title menu and logo at example) www.sgemsocial.org ! The parts overlap when is going to mobile version ... how I should solve this problem? ...how would you resolve it? Is exist also on other cases on this site!

Thank you and greetings everyone!

**Comment by mahagr** [comment]
Your question has nothing to do with toolbox library, please use the forum in `rockettheme.com` for paid template support.
