### ISSUE TITLE
Some of my RokSprocket Modules are not working when the web site is online ...

### ISSUE THREAD

**Issue by dimidino** [rockettheme/toolbox#16]
Hello again!

( And again, I'm not sure if this is the right forum, please if it is not - tell me the right one and you do not hate me! ;) )

And another case from me! ( our unattractive site - www.sgemsocial.org ) Lately, i have problems with RokSprocket Modules that simple are not working when the web site is online, and work very well on the local host! the parameters and options of the site are identical, I compared them many times!

Greetings to everyone here!

**Comment by mahagr** [comment]
Your question has nothing to do with toolbox library, please use the forum in www.rockettheme.com for paid template support.
