### ISSUE TITLE
preventing UniformResourceLocator from resolving paths outside of defined scheme paths

### ISSUE THREAD

**Issue by alexweissman** [rockettheme/toolbox#8]
I've been playing around with `UniformResourceLocator` more, and I'm trying to use it to resolve user-supplied paths.  However, the way I'm using it now opens me up to a directory traversal attack:

```
        $locator = new UniformResourceLocator('/path/to/document/root');
        
        // Adds 'assets' to the searchable paths
        $locator->addPath('assets', '', 'assets');
        
        // Initialize streams
        ReadOnlyStream::setLocator($locator);
        $sb = new StreamBuilder([
            'assets' => '\\RocketTheme\\Toolbox\\StreamWrapper\\ReadOnlyStream'
        ]);

        $url = "assets://../secret.txt";

        echo file_get_contents($locator->findResource($url));
        // prints contents of '/path/to/document/root/assets/../secret.txt'
```

Is there, or should there be, an option to prevent the locator from resolving paths outside of one of the designated directories?

**Comment by mahagr** [comment]
I agree that these should be prevented.

**Comment by alexweissman** [comment]
One solution would be:

1. Resolve each potential absolute path match using `realpath`.  For example, when we match `assets://../secret.txt` to path `/path/to/document/root/assets/`, and get the corresponding absolute path `/path/to/document/root/assets/../secret.txt`, this would be resolved by `realpath` as `/path/to/document/root/secret.txt`.

2. If the search path (`/path/to/document/root/assets/`) is not a substring of the resolved absolute path (`/path/to/document/root/secret.txt`), then we know that we've traversed outside of the directory.  Thus, this would be considered "not a match", and we would move on to the next search path.

There might be some edge cases I'm not considering, but this would be the basic strategy.

**Comment by alexweissman** [comment]
It turns out that `realpath` was not a good solution because it cannot resolve relative paths.  So, I ended up using the `normalizePath` method as implemented in https://github.com/thephpleague/flysystem.

**Comment by alexweissman** [comment]
Actually, when I think about it more, should we just disallow directory traversal entirely?  Even if after resolution, it puts someone back in a valid directory again?

For example, suppose `assets://` maps to `/path/web/assets/`.  Should `assets://../assets/base.txt` be permitted?

**Comment by mahagr** [comment]
Yes, `realpath()` doesn't work as it also requires that the file actually exists by using absolute path.

Right now no `..` is permitted at all, but we may want to permit it under subdirectories as long as path still under the stream.

Please do not add requirement for another library, even if I like the league classes, it shouldn't be requirement for this library.

**Comment by mahagr** [comment]
I took a bit different approach, should work now.
